### ISSUE TITLE
Use html-to-vdom

### ISSUE THREAD

**Issue by TimBeyer** [azer/html-patcher#1]
Just wanted to propose to use https://github.com/TimBeyer/html-to-vdom for doing the conversion from template to virtual DOM node.
I'd love to get some more feedback on the library and evolve it.
So far it's quite well tested, takes care of some special cases like data attributes and it's even used in production.

I expose a promise based interface, but you could easily `nodeify` it again if you prefer that.

What do you think?

**Comment by azer** [comment]
it looks great Tim! I'll use it, although would keep also maintaining this because I prefer functions over promises as interfaces. thanks for sharing it since I'd like to learn & inspire from your experience!
